openapi: 3.0.0
info:
  title: Mock Target API
  version: 1.0.0
paths:
  /:
    get:
      description: View a personalized greeting for the specified or guest user.
      responses:
        "200":
          description: Success
